### ISSUE TITLE
Each task prints the headers of the request

### ISSUE THREAD

**Issue by rigeliux** [cheprasov/php-parallel#13]
Hi!
First of all, awesome package!
Second: im using your package to make some parrallel requests (cURL), but everytime a task its completed, the headers of the response are shown:
Example:
http://www.bitwit-ws.com/tuguruu/public_html/buscar?keywords=xbox

Server specs:
CentOS 6.8
WHM 62 (easyapache4)
Redis as Storage

**Comment by cheprasov** [comment]
Hi, @rigeliux 
Thanks for comment. But, I think, it is not issue of the package. 
Could you send me your code to email, I will check it.
acheprasov84@gmail.com
Thanks.
